addSbtPlugin("com.eed3si9n"      % "sbt-assembly"        % "0.14.10")
addSbtPlugin("com.lucidchart"    % "sbt-scalafmt"        % "1.16")
addSbtPlugin("org.scoverage"     % "sbt-scoverage"       % "1.6.0")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph"% "0.10.0-RC1")
addSbtPlugin("de.gccc.sbt" % "sbt-jib" % "0.8.0")
